from enum import Enum


class RiskLevel(str, Enum):
    GREEN = "GREEN"
    AMBER = "AMBER"
    RED = "RED"
    UNKNOWN = "UNKNOWN"


class ContractStatus(str, Enum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    OCR_COMPLETE = "OCR_COMPLETE"
    EXTRACTION_COMPLETE = "EXTRACTION_COMPLETE"
    REVIEW_READY = "REVIEW_READY"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ERROR = "ERROR"


class ClauseType(str, Enum):
    CONFIDENTIALITY = "CONFIDENTIALITY"
    INDEMNITY = "INDEMNITY"
    LIABILITY = "LIABILITY"
    TERMINATION = "TERMINATION"
    GOVERNING_LAW = "GOVERNING_LAW"
    DISPUTE_RESOLUTION = "DISPUTE_RESOLUTION"
    FORCE_MAJEURE = "FORCE_MAJEURE"
    PAYMENT = "PAYMENT"
    INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY"
    NON_COMPETE = "NON_COMPETE"
    NON_SOLICITATION = "NON_SOLICITATION"
    WARRANTY = "WARRANTY"


class UserRole(str, Enum):
    JUNIOR_LAWYER = "junior_lawyer"
    SENIOR_LAWYER = "senior_lawyer"
    ADMIN = "admin"
