import os

files = [
    # core
    "contracts_platform/__init__.py",
    "contracts_platform/core/__init__.py",
    "contracts_platform/core/constants.py",
    "contracts_platform/core/exceptions.py",
    "contracts_platform/core/config.py",
    "contracts_platform/core/encryption.py",
    "contracts_platform/core/security.py",
    "contracts_platform/core/logging.py",
    "contracts_platform/core/tracing.py",
    # api
    "contracts_platform/api/__init__.py",
    "contracts_platform/api/main.py",
    "contracts_platform/api/dependencies.py",
    "contracts_platform/api/middleware/__init__.py",
    "contracts_platform/api/middleware/logging_middleware.py",
    "contracts_platform/api/middleware/tracing_middleware.py",
    "contracts_platform/api/middleware/rate_limit_middleware.py",
    "contracts_platform/api/routers/__init__.py",
    "contracts_platform/api/routers/auth.py",
    "contracts_platform/api/routers/contracts.py",
    "contracts_platform/api/routers/clauses.py",
    "contracts_platform/api/routers/users.py",
    "contracts_platform/api/routers/admin.py",
    "contracts_platform/api/routers/webhooks.py",
    "contracts_platform/api/schemas/__init__.py",
    "contracts_platform/api/schemas/auth.py",
    "contracts_platform/api/schemas/contract.py",
    "contracts_platform/api/schemas/clause.py",
    "contracts_platform/api/schemas/user.py",
    "contracts_platform/api/schemas/risk.py",
    # auth
    "contracts_platform/auth/__init__.py",
    "contracts_platform/auth/jwt_handler.py",
    "contracts_platform/auth/oauth2.py",
    "contracts_platform/auth/rbac.py",
    "contracts_platform/auth/api_key_manager.py",
    # db - mongodb
    "contracts_platform/db/__init__.py",
    "contracts_platform/db/mongodb/__init__.py",
    "contracts_platform/db/mongodb/client.py",
    "contracts_platform/db/mongodb/models.py",
    "contracts_platform/db/mongodb/repositories/__init__.py",
    "contracts_platform/db/mongodb/repositories/contract_repo.py",
    "contracts_platform/db/mongodb/repositories/audit_repo.py",
    "contracts_platform/db/mongodb/repositories/cost_repo.py",
    "contracts_platform/db/mongodb/migrations/__init__.py",
    "contracts_platform/db/mongodb/migrations/001_initial_indexes.py",
    # db - postgresql
    "contracts_platform/db/postgresql/__init__.py",
    "contracts_platform/db/postgresql/client.py",
    "contracts_platform/db/postgresql/models.py",
    "contracts_platform/db/postgresql/repositories/__init__.py",
    "contracts_platform/db/postgresql/repositories/rule_repo.py",
    "contracts_platform/db/postgresql/repositories/jurisdiction_repo.py",
    "contracts_platform/db/postgresql/migrations/__init__.py",
    "contracts_platform/db/postgresql/migrations/env.py",
    "contracts_platform/db/postgresql/migrations/versions/__init__.py",
    "contracts_platform/db/postgresql/migrations/versions/0001_initial_schema.py",
    # db - qdrant
    "contracts_platform/db/qdrant/__init__.py",
    "contracts_platform/db/qdrant/client.py",
    "contracts_platform/db/qdrant/collections.py",
    "contracts_platform/db/qdrant/embedding_registry.py",
    "contracts_platform/db/qdrant/repositories/__init__.py",
    "contracts_platform/db/qdrant/repositories/clause_vector_repo.py",
    "contracts_platform/db/qdrant/repositories/tenant_manager.py",
    # db - neo4j
    "contracts_platform/db/neo4j/__init__.py",
    "contracts_platform/db/neo4j/client.py",
    "contracts_platform/db/neo4j/models.py",
    "contracts_platform/db/neo4j/repositories/__init__.py",
    "contracts_platform/db/neo4j/repositories/party_repo.py",
    "contracts_platform/db/neo4j/repositories/contract_graph_repo.py",
    "contracts_platform/db/neo4j/repositories/clause_graph_repo.py",
    "contracts_platform/db/neo4j/cypher/party_queries.cypher",
    "contracts_platform/db/neo4j/cypher/conflict_queries.cypher",
    "contracts_platform/db/neo4j/cypher/risk_queries.cypher",
    # pipeline
    "contracts_platform/pipeline/__init__.py",
    "contracts_platform/pipeline/cost_tracker.py",
    "contracts_platform/pipeline/ocr/__init__.py",
    "contracts_platform/pipeline/ocr/extractor.py",
    "contracts_platform/pipeline/ocr/confidence.py",
    "contracts_platform/pipeline/ocr/table_extractor.py",
    "contracts_platform/pipeline/ocr/providers/__init__.py",
    "contracts_platform/pipeline/ocr/providers/azure_ocr_provider.py",
    "contracts_platform/pipeline/clause_extraction/__init__.py",
    "contracts_platform/pipeline/clause_extraction/extractor.py",
    "contracts_platform/pipeline/clause_extraction/validator.py",
    "contracts_platform/pipeline/clause_extraction/fallback_parser.py",
    "contracts_platform/pipeline/clause_extraction/missing_clause_detector.py",
    "contracts_platform/pipeline/recommendation/__init__.py",
    "contracts_platform/pipeline/recommendation/generator.py",
    "contracts_platform/pipeline/recommendation/wording_retriever.py",
    "contracts_platform/pipeline/recommendation/fix_suggester.py",
    # orchestration
    "contracts_platform/orchestration/__init__.py",
    "contracts_platform/orchestration/graph.py",
    "contracts_platform/orchestration/state.py",
    "contracts_platform/orchestration/nodes/__init__.py",
    "contracts_platform/orchestration/nodes/playbook_check_node.py",
    "contracts_platform/orchestration/nodes/vector_check_node.py",
    "contracts_platform/orchestration/nodes/graph_check_node.py",
    "contracts_platform/orchestration/nodes/risk_aggregator_node.py",
    "contracts_platform/orchestration/nodes/recommendation_node.py",
    "contracts_platform/orchestration/nodes/explainability_node.py",
    "contracts_platform/orchestration/scoring/__init__.py",
    "contracts_platform/orchestration/scoring/weights.py",
    "contracts_platform/orchestration/scoring/risk_calculator.py",
    "contracts_platform/orchestration/checkpoints/__init__.py",
    "contracts_platform/orchestration/checkpoints/redis_checkpointer.py",
    # workers
    "contracts_platform/workers/__init__.py",
    "contracts_platform/workers/celery_app.py",
    "contracts_platform/workers/queues.py",
    "contracts_platform/workers/retry_policy.py",
    "contracts_platform/workers/dead_letter.py",
    "contracts_platform/workers/progress_tracker.py",
    "contracts_platform/workers/tasks/__init__.py",
    "contracts_platform/workers/tasks/ingest_task.py",
    "contracts_platform/workers/tasks/ocr_task.py",
    "contracts_platform/workers/tasks/clause_extraction_task.py",
    "contracts_platform/workers/tasks/review_orchestration_task.py",
    "contracts_platform/workers/tasks/recommendation_task.py",
    "contracts_platform/workers/tasks/post_decision_task.py",
    "contracts_platform/workers/tasks/cleanup_task.py",
    # file_handling
    "contracts_platform/file_handling/__init__.py",
    "contracts_platform/file_handling/validator.py",
    "contracts_platform/file_handling/duplicate_detector.py",
    "contracts_platform/file_handling/storage.py",
    "contracts_platform/file_handling/temp_storage.py",
    # notifications
    "contracts_platform/notifications/__init__.py",
    "contracts_platform/notifications/websocket_manager.py",
    # scripts
    "scripts/__init__.py",
    "scripts/seed_playbook_rules.py",
    "scripts/init_qdrant_collections.py",
    "scripts/init_neo4j_schema.py",
    "scripts/generate_api_key.py",
    # tests
    "tests/__init__.py",
    "tests/conftest.py",
    "tests/unit/__init__.py",
    "tests/unit/test_clause_validator.py",
    "tests/unit/test_risk_calculator.py",
    "tests/unit/test_file_validator.py",
    "tests/unit/test_jwt_handler.py",
    "tests/unit/test_duplicate_detector.py",
    "tests/integration/__init__.py",
    "tests/integration/test_contract_upload_flow.py",
    "tests/integration/test_ocr_pipeline.py",
    "tests/integration/test_langgraph_orchestration.py",
    "tests/integration/test_db_repositories.py",
    "tests/integration/test_celery_tasks.py",
    "tests/e2e/__init__.py",
    "tests/e2e/test_full_pipeline.py",
    "tests/e2e/fixtures/.gitkeep",
    # docker
    "docker/Dockerfile.api",
    "docker/Dockerfile.worker",
    "docker/docker-compose.yml",
    "docker/docker-compose.test.yml",
    # github actions
    ".github/workflows/ci.yml",
    ".github/workflows/qa-merge-check.yml",
]

created = 0
for f in files:
    d = os.path.dirname(f)
    if d:
        os.makedirs(d, exist_ok=True)
    if not os.path.exists(f):
        open(f, "w").close()
        created += 1

print(f"Done — {created} files created, {len(files) - created} already existed")
print(f"Total files: {len(files)}")
